spring:
  profiles:
    include: oauth

  thymeleaf:
    cache: false

  servlet:
    multipart:
      enabled: true
      location: /Users/kimkiyun/Desktop
      max-request-size: 30MB
      max-file-size: 10MB

  datasource:
    #h2 setting
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/springsecurity
#    url: jdbc:h2:mem:springsecurity
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          format_sql: true
          default_batch_fetch_size: 1000
      show-sql: true
    open-in-view: false

logging.level:
  org.hibernate.SQL: debug

server:
  port: 8081
