spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 933509254527-84glf4rdbgt2othk9rhiabq0mh9sr7tj.apps.googleusercontent.com
            client-secret: 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
            scope: email
          kakao:
            client-id: 16ca285777b6539ee18748fc388cecf9
            client-secret: PmJc2NAO9TvDBcK8lb9MhD4LVulQLXUn
            redirect-uri: http://localhost:8081/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope: account_email, profile_nickname, profile_image

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id