spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 933509254527-84glf4rdbgt2othk9rhiabq0mh9sr7tj.apps.googleusercontent.com
            client-secret: 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
            scope: email
          kakao:
            client-id: 9d1f2abed3ce46931ff7abf4b7f8a31a
            client-secret: iMWiBMuZMA4uakDWL7wVrVFE5xjmh18C
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope: account_email, profile_nickname, profile_image

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id